---
- hosts: localhost
  tasks:
  - name: "Making directory"
    shell: mkdir -p {{app_dir}}/logs {{app_dir}}/steam_install
  - name: "Installing Rust Server"
    shell: "steamcmd +force_install_dir {{app_dir}}/rustserver +login anonymous +app_update 258550 -validate +quit"
