---
- hosts: localhost
  tasks:
  - name: "Remove Map Files"
    shell: "rm -rf {{app_dir}}/rustserver/server/{{identity}}/*.map"
  - name: "Remove Sav Files"
    shell: "rm -rf {{app_dir}}/rustserver/server/{{identity}}/*.sav*"