---
- hosts: localhost
  tasks:
  - name: "Stopping Rust Server!"
    shell: ps aux | grep -ie RustDedicated | grep -v grep | awk '{print $2}' | xargs kill -9
  - name: "Starting up rust server"
    shell: cd {{app_dir}}/rustserver/ && nohup ./RustDedicated -batchmode +server.ip 0.0.0.0 +server.port 28015 +server.tickrate 10 +server.hostname "{{hostname}}" +server.identity "{{identity}}" +server.seed {{seed}} +server.maxplayers {{players}} +server.worldsize {{worldsize}} +server.saveinterval 600 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "{{rcon_password}}" +server.description "{{description}}" +server.headerimage "{{header_image}}" &> {{app_dir}}/logs/rustserver-services.log &
